version: '3.4'

services:
  recall-zipkin:
    image: openzipkin/zipkin-slim:latest


  recall-seq:
    image: datalust/seq:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"


  recall-sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  
  recall-envoygateway:
    image: envoyproxy/envoy:v1.11.1
    extra_hosts:
      - "host.docker.internal:host-gateway"


  recall-envoygateway-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:recall-envoygateway"
    depends_on:
      - recall-envoygateway


  recall-textitemapi:
    image: recall-textitemapi
    build:
      context: .
      dockerfile: Contrib/TextItem.Api/Dockerfile


  recall-textitemapi-dapr:
    image: "daprio/daprd:1.9.4"
    network_mode: "service:recall-textitemapi"
    depends_on:
      - recall-textitemapi
  

  recall-servicestatus:
    image: recall-servicestatus
    build:
      context: .
      dockerfile: Infrastructure/ServiceStatus/Dockerfile
      
      
  

